/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apic663b6d9",
            "endpoint": "https://fk4ioh9y1f.execute-api.us-east-1.amazonaws.com/amplifyenv",
            "region": "us-east-1"
        },
        {
            "name": "apibc3cf41b",
            "endpoint": "https://ag5bd1sqyg.execute-api.us-east-1.amazonaws.com/amplifyenv",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:20b2318f-8142-4d0e-aa27-bac14637efbd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_y5pr0i0aV",
    "aws_user_pools_web_client_id": "2l4b9phm95rlp8n35livvcbbp6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "GIVEN_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "islandserenity-20240811165554-hostingbucket-amplifyenv",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d29u8zr341i019.cloudfront.net"
};


export default awsmobile;
